version: '3.9'
services:
  app:
    container_name: app_landing-page-product
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app
    volumes: 
      - .:/app
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
